SEED = 1
BATCH_SIZE = 64

WORKDIR = "./"


MAP_ACT_ROUTE = "act_planck_dr5.01_s08s18_AA_f220_daynight_fullivar.fits"
DR5_CLUSTERS_ROUTE = "DR5_cluster-catalog_v1.1.fits"
SGA_ROUTE = "SGA-2020.fits"
ACT_MCMF_ROUTE = "act_mcmf_catalog.fits"

MAP_ACT_FILENAME = "map_act.fits"
DR5_CLUSTERS_FILENAME = "dr5.fits"
SGA_FILENAME = "sga.fits"
ACT_MCMF_FILENAME = "act_mcmf.fits"

ARCHIVE_DR5_URL = "https://lambda.gsfc.nasa.gov/data/suborbital/ACT/ACT_dr5/"
ACT_MCMF_URL = "https://vizier.cds.unistra.fr/viz-bin/nph-Cat/txt/J/A+A/690/A322/catalog"

[LEGACY_SURVEY]
LAYER = "unwise-neo7"
# LAYER = "vlass1.2"
BANDS = "griz"

[comet]
API_KEY = "api-key"
WORKSPACE = "workspace-name"
